# Generated by Django 3.2.8 on 2021-10-05 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
                ('grupo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kardex.grupo')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonsocial', models.CharField(max_length=30)),
                ('ruc', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=40)),
                ('ciudad', models.CharField(max_length=20)),
                ('celular1', models.CharField(max_length=15)),
                ('celular2', models.CharField(max_length=15)),
                ('telefono1', models.CharField(max_length=15)),
                ('telefono2', models.CharField(max_length=15)),
                ('contacto', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=50)),
                ('paginaweb', models.CharField(max_length=30)),
                ('banco', models.CharField(max_length=30)),
                ('cuenta', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedors',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medida', models.CharField(choices=[('BJ', 'BALDE'), ('BG', 'BOLSA'), ('BX', 'CAJA'), ('KGM', 'KILOGRAMO'), ('LTR', 'LITRO'), ('NIU', 'UNIDAD')], max_length=20)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='producto')),
                ('maximo', models.IntegerField()),
                ('minimo', models.IntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kardex.grupo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kardex.marca')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toperacion', models.CharField(choices=[('VENTA', 'VENTA NACIONAL'), ('COMPRA', 'COMPRA NACIONAL'), ('DEVOLUCION', 'DEVOLUCION RECIBIDA'), ('OTROS', 'OTROS')], max_length=50)),
                ('tcomprobante', models.CharField(choices=[('FACTURA', 'FACTURA'), ('BOLETA', 'BOLETA DE VENTA'), ('GUIA', 'GUIA DE REMISION'), ('OTROS', 'OTROS')], max_length=20)),
                ('fecha', models.DateField()),
                ('serie', models.CharField(max_length=8)),
                ('numero', models.CharField(max_length=10)),
                ('ecantidad', models.IntegerField()),
                ('ecostou', models.FloatField()),
                ('ecostot', models.FloatField()),
                ('xcantidad', models.IntegerField()),
                ('xcostou', models.FloatField()),
                ('xcostot', models.FloatField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kardex.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kardex.proveedor')),
            ],
            options={
                'verbose_name': 'Kardex',
                'verbose_name_plural': 'Kardexs',
            },
        ),
    ]
